'use strict';
window.ygb_import(function(lib,game,ui,get,ai,_status){
    if(!lib.qhlypkg){
        lib.qhlypkg = [];
    }
    var taici = {
    //原皮台词
        'lyz_zhaoyun':{
                    'lyzlongying':{
                        order:1,
                        content:'①银枪所至，千夫不敌！<br>②抽身而退，万军难挡！',
                    },
                    'lyzhunyou':{
                        order:2,
                        content:'①八方风雨，天涯何归？<br>②滴水不漏，稳若泰山！',
                    },
                    'lyzcuizhen':{
                        order:3,
                        content:'①无知小儿，先站稳阵脚再来吧！<br>②是谁给你的勇气，来跟本将军叫阵！',
                    },
                    'lyzchengyu':{
                        order:4,
                        content:'①一人一枪一匹马，疆场尽驰骋！<br>②龙升九天，马踏飞燕！',
                    },
                    'die':{
                        content:'北伐大业未定，末将实难心安……',
                    }
        },
        'lyz_shen_diaochan':{
                    'lyzyuhun':{
                        order:1,
                        content:'①就让小女为将军献上一舞。<br>②你愿意为我死吗？',
                    },
                    'lyzhuanmei':{
                        order:2,
                        content:'①行时风摆杨柳，静时文雅有余。<br>②回眸一笑百媚生，六宫粉黛无颜色。',
                    },
                    'lyzyuepo':{
                        order:3,
                        content:'①纵有闭月之貌，又能伴心上人几时？<br>②花前月下，愿君无恙。',
                    },
                    'die':{
                        content:'对不起，我已经回不去了……',
                    }
        },
        'lyz_shen_zhangliao':{
                    'lyzcuifeng':{
                        order:1,
                        content:'①夺敌军锐气，杀敌方士气！<br>②尖锐之势，吾亦可一人夺之！',
                    },
                    'lyzxiasha':{
                        order:2,
                        content:'①吴人惧我，如稚童之惧梦魇！<br>②张辽来也，还不速速逃命？',
                    },
                    'lyzzhijue':{
                        order:3,
                        content:'①东吴虽锐挡三军，吾亦不惧！<br>②尔比之东吴十万大军如何？',
                    },
                    'die':{
                        content:'我也有被孙仲谋所伤之时？',
                    }
        },
        'lyz_shen_gaodayihao':{
                    'lyzjuejing':{
                        order:1,
                        content:'①龙战于野，其血玄黄！',
                    },
                    'lyzlonghun':{
                        order:2,
                        content:'①千里一怒，红莲灿世！<br>②腾龙行云，首尾不见。<br>③潜龙于渊，摄灵愈伤。<br>④金甲映日，驱邪去秽！',
                    },
                    'lyzzhanjiang':{
                        order:3,
                        content:'①龙战于野，其血玄黄！',
                    },
                    'die':{
                        content:'血染鳞甲，龙坠九天……',
                    }
        },
        'lyz_zhugeliang':{
                    'lyzwendao':{
                        order:1,
                        content:'①披星戴月，力启洪荒。<br>②天衍四九，人遁其一。',
                    },
                    'lyzzhaoce':{
                        order:2,
                        content:'①不可擅动，吾自有计。<br>②虚而示虚，疑中生疑。',
                    },
                    'lyzkuitian':{
                        order:3,
                        content:'①风随吾意，变化无常！<br>②天公助我，雾笼满江。',
                    },
                    'die':{
                        content:'星光昏暗，吾命不久矣。',
                    }
        },
        'lyz_mayunlu':{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①贼人，是不是被本姑娘给吓破胆了呀？<br>②看我不好好杀杀你的威风！',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'子龙哥哥，救我！',
                    }
        },
        'lyz_zhouyu':{
                    'lyzxinlve':{
                        order:1,
                        content:'①麒麟出世，此天将兴东吴也。<br>②麒麟子孙，终将执掌中原大地！',
                    },
                    'lyzyanjie':{
                        order:2,
                        content:'①火借风势，风助火威。<br>②权势、荣耀、欲望，都在这熊熊业火中焚尽吧！',
                    },
                    'die':{
                        content:'天下已三分，我的使命已结束了……',
                    }
        },
        'lyz_shen_lvbu':{
                    'lyznuozhan':{
                        order:1,
                        content:'①破绽百出，安敢妄言？',
                    },
                    'lyzzhenguan':{
                        order:2,
                        content:'①凭关镇敌，万夫莫开！<br>②雄霸虎牢，一将当关！',
                    },
                    'lyzxiaohu':{
                        order:3,
                        content:'①方天画戟，振我神威！<br>②明光宝甲，护我神躯。',
                    },
                    'lyznewjiwu':{
                        order:4,
                        content:'①力之所待，蓄势而发！<br>②利刀缮甲，东山再起。',
                    },
                    'lyzkuipo':{
                        order:5,
                        content:'①吾怒如火，焚汝残躯！<br>②神魔天征，挡我者死！',
                    },
                    'wumou':{
                        order:6,
                        content:'（默认）',
                    },
                    'new_liyu':{
                        order:7,
                        content:'（默认）',
                    },
                    'die':{
                        content:'魂飞魄散，且入轮回……',
                    }
        },
        'lyz_lingju':{
                    'lyzwuren':{
                        order:1,
                        content:'①容貌易识，人心难测。<br>②种种孽缘，终究要算清。',
                    },
                    'lyzhongshang':{
                        order:2,
                        content:'①彼岸照明月，炙火焚尘心。<br>②无缘何缘起，竭缘不必续。',
                    },
                    'die':{
                        content:'绝艳佳容天涯路，只信人间别离苦。',
                    }
        },
        'lyz_caiwenji':{
                    'lyzchengxin':{
                        order:1,
                        content:'①书卷识人，才学默心。<br>②琴棋书画，妾身各得其法。',
                    },
                    'lyzfuqing':{
                        order:2,
                        content:'①虎士成林，何惜疾足一骑。<br>②翩翩吹我衣，肃肃入我耳。',
                    },
                    'die':{
                        content:'今生悲苦，总算完结了。',
                    }
        },
        'lyz_zhenji':{
                    'lyzshenhuang':{
                        order:1,
                        content:'①泪洒梨花前，情愁随花落。<br>②若错花期，花将不再。',
                    },
                    'lyzjinghong':{
                        order:2,
                        content:'①捧月华如胧，拾芬芳其中。<br>②沐水芙蓉，避于云雾。',
                    },
                    'die':{
                        content:'昔日佳人没，今日洛水寒。',
                    }
        },
        'lyz_daqiao':{
                    'lyzyurong':{
                        order:1,
                        content:'①此生容颜，只为君留。<br>②古玉沁色，羞颜暖心。',
                    },
                    'lyzfuhua':{
                        order:2,
                        content:'①丽光耀八溪，玉流通九曲。<br>②流逸飘然，罗裳依依。',
                    },
                    'die':{
                        content:'最苦，便是与将军分别......',
                    }
        },
        'lyz_xiaoqiao':{
                    'lyzfangze':{
                        order:1,
                        content:'①花醉山林，香泽弥漫。<br>②暖香幽幽，驱冷散寒。',
                    },
                    'lyzfumeng':{
                        order:2,
                        content:'①桃花随风逝，飘落待归期。<br>②昨日繁花盛，今日萧萧落。',
                    },
                    'die':{
                        content:'鹊桥孤影，公瑾何时归.......',
                    }
        },
        'lyz_sunshangxiang':{
                    'lyzbeiwu':{
                        order:1,
                        content:'①小女就爱这舞刀弄枪。<br>②弓腰武美姬，巾帼不输君。',
                    },
                    'lyzjiaogong':{
                        order:2,
                        content:'①花间皎洁，快步无影。<br>②体态轻盈，出招无形。',
                    },
                    'die':{
                        content:'下次比武，我可不会输给哥哥。',
                    }
        },
        'lyz_huangyueying':{
                    'lyzzhiying':{
                        order:1,
                        content:'①一计再连一计！<br>②机巧谋略，我皆不输于你。',
                    },
                    'lyzjinxin':{
                        order:2,
                        content:'①神智泉涌，取之不绝。<br>②博览群书，集智慧之大成。',
                    },
                    'die':{
                        content:'今生幸得先生眷顾，来世我们再……',
                    }
        },
        'lyz_simayi':{
                    'lyzyinfeng':{
                        order:1,
                        content:'①哼，作法自毙。<br>②这可由不得你！',
                    },
                    'lyztaohui':{
                        order:2,
                        content:'①哼，尽在我的掌握。<br>②别挣扎了，一切都是徒劳的。',
                    },
                    'die':{
                        content:'才大难用，处处受制，可悲啊……',
                    }
        },
        'lyz_guojia':{
                    'lyzchouji':{
                        order:1,
                        content:'①吾自幼习与长者交谈，获益颇丰。<br>②智者，当有高瞻远瞩，推演时局之能。',
                    },
                    'lyzmingfu':{
                        order:2,
                        content:'①身负天妒之才，腹怀奇策良谋。<br>②大限将至乃天命，尚有一计定辽东。',
                    },
                    'die':{
                        content:'行事逆天，亦知天命不眷……',
                    }
        },
        'lyz_machao':{
                    'lyztianwei':{
                        order:1,
                        content:'①良驹健儿，破营溃军！<br>②纵使敌酋如何防备，也难阻我马家雄师！',
                    },
                    'lyzxiaohun':{
                        order:2,
                        content:'①先骑克敌，不避险难！<br>②全力冲锋，先声夺人！',
                    },
                    'die':{
                        content:'血仇无报，坎坷一生，哎……',
                    }
        },
        'lyz_huatuo':{
                    'lyzqinggu':{
                        order:1,
                        content:'①有的放矢，对症下药。<br>②让我来试一试。',
                    },
                    'lyzhuomai':{
                        order:2,
                        content:'①血脉流通，则诸病不生。<br>②正本清源，则药到病除。',
                    },
                    'lyztiantong':{
                        order:3,
                        content:'①大济济世，上医医国。<br>②妙手回春，起死回生。',
                    },
                    'die':{
                        content:'医术，真的能救得了世人吗？',
                    }
        },
        'lyz_caojie':{
                    'lyzxianmu':{
                        order:1,
                        content:'①惠国惠民路，我与君同行。<br>②尽毕生所学，消百姓疾愁。',
                    },
                    'lyzfengjun':{
                        order:2,
                        content:'①哥哥，为何苦苦相逼？<br>②吾誓与此玺共存亡！',
                    },
                    'die':{
                        content:'苍天有眼，绝不能让你长久……',
                    }
        },
        'lyz_caocao':{
                    'lyzbabei':{
                        order:1,
                        content:'①鸿鹄大志，几人能懂？<br>②奸略逐鹿原，雄才扫狼烟！',
                    },
                    'lyztianfu':{
                        order:2,
                        content:'①宁我负人，毋人负我！<br>②乱世天下，能者居之。',
                    },
                    'die':{
                        content:'霸业未竟，孤，心不甘！',
                    }
        },
        'lyz_liubei':{
                    'lyzzhaoren':{
                        order:1,
                        content:'①仁施天下，德及众生。<br>②仁者，自当胸怀天下。',
                    },
                    'lyzlongjie':{
                        order:2,
                        content:'①怒伤心肝，也阻止不了这复仇之火！<br>②灼艾分痛失，虽万劫，亦杀之！',
                    },
                    'die':{
                        content:'夷陵之火，焚尽了我一生心力……',
                    }
        },
        'lyz_sunjian':{
                    'lyzjinzheng':{
                        order:1,
                        content:'①止戈为武，平尽天下不平事！<br>②捐躯成烈，无愧世间有愧人！',
                    },
                    'lyzyilie':{
                        order:2,
                        content:'①泉台舞戈斗阎罗，且招旧部为鬼雄！<br>②谁道死去万事空？英魂依旧守江东！',
                    },
                    'die':{
                        content:'孙氏当兴，行不在我……',
                    }
        },
        'lyz_zhangjiao':{
                    'lyzluanshi':{
                        order:1,
                        content:'①拦我天公者，天诛之！<br>②追云逐电，雷动九天！',
                    },
                    'huangtian':{
                        order:2,
                        content:'（默认）',
                    },
                    'lyztaiping':{
                        order:3,
                        content:'①救苍生于水火，平天下于乱世！<br>②顺天应命，唯我黄天！',   
                    },
                    'die':{
                        content:'黄天，竟不助我……',
                    }
        },
        'lyz_zhangchunhua':{
                    'lyzcanqing':{
                        order:1,
                        content:'①博弈此生，终至无情。<br>②此情已逝，故来决绝！',
                    },
                    'lyzwanai':{
                        order:2,
                        content:'①情随伤而逝，恨随痛而至。<br>②春华已老红颜去，此恨绵绵无绝期。',
                    },
                    'die':{
                        content:'不怕花容去，只怕情难续……',
                    }
        },
        'lyz_luxun':{
                    'lyzdingqian':{
                        order:1,
                        content:'①谦谦有礼，婉婉有仪。<br>②失之东隅，收之桑榆。',
                    },
                    'lyzguilv':{
                        order:2,
                        content:'①虚怀若谷，戒骄戒躁。<br>②天下万物生于有，有生于无。',
                    },
                    'die':{
                        content:'我何以……至此？',
                    }
        },
        'lyz_shen_simayi':{
                    'lyzchouyi':{
                        order:1,
                        content:'①因果有律，世间无常。<br>②万物无异，强弱有别。',
                    },
                    'lyztianqian':{
                        order:2,
                        content:'①轻举妄为，徒招横祸。',
                    },
                    'lyzdikun':{
                        order:3,
                        content:'①逆势而为，不自量力。',
                    },
                    'lyzguiyuan':{
                        order:4,
                        content:'①吾之身前，万籁俱寂。<br>②吾之身后，了无生机！',
                    },
                    'die':{
                        content:'生门一闭，唯有赴死……',
                    }
        },
        'lyz_zhangxingcai':{
                    'lyzlingying':{
                        order:1,
                        content:'①国仇家恨，今日一并算清！<br>②卫境汉土，凭我长枪！',
                    },
                    'lyzxingxuan':{
                        order:2,
                        content:'①夫君无断，妾身亲为。<br>②助君大业，立德唯心。',
                    },
                    'die':{
                        content:'誓死……我也要守卫这山河！',
                    }
        },
        'lyz_diaochan':{
                    'lyzyinghuo':{
                        order:1,
                        content:'①凤仪亭风波，巧生两嫌隙。<br>②将军勇猛，妾身可是看好你的~',
                    },
                    'lyzxingyun':{
                        order:2,
                        content:'①月蝶情长，相思入心间。<br>②舞带飘飘心波动，月色皎皎情前记。',
                    },
                    'die':{
                        content:'乱世美人颜，飘零玉骨埋。',
                    }
        },
        'lyz_shen_zhouyu':{
                    'lyzningxian':{
                        order:1,
                        content:'①（琴声）<br>②（琴声）',
                    },
                    'lyzjueyin':{
                        order:2,
                        content:'①（琴声）<br>②（琴声，业火声）',
                    },
                    'lyzdizui':{
                        order:3,
                        content:'①浮生罪业，皆归灰烬！',
                    },
                    'die':{
                        content:'心已乱，琴弦断……',
                    }
        },
        'lyz_yangguangweiliang':{
                    'lyzzhiguo':{
                        order:1,
                        content:'（暂无）',
                    },
                    'lyzpingfang':{
                        order:2,
                        content:'（暂无）',
                    },
                    'lyzqingyan':{
                        order:3,
                        content:'（暂无）',
                    },
                    'die':{
                        content:'（暂无）',
                    }
        },
        'lyz_zhangfei':{
                    'lyzfengxuan':{
                        order:1,
                        content:'①丈八蛇矛在吾手，汝等害怕了吗？<br>②贼众百万，吾亦不放在眼里！',
                    },
                    'lyztiansha':{
                        order:2,
                        content:'①百万军中，看我取上将首级！<br>②吾，以一敌千！',
                    },
                    'die':{
                        content:'终是小人难防啊……',
                    }
        },
        'lyz_yjlgt':{
                    'lyzzhidian':{
                        order:1,
                        content:'①读！教！程！<br>②不看教程，不必多言。',
                    },
                    'lyzshulun':{
                        order:2,
                        content:'①突袭检查！<br>②谁在开车？统统禁言。',
                    },
                    'lyzjianji':{
                        order:3,
                        content:'①你没了。<br>②《死亡笔记》新添一员。',
                    },
                    'die':{
                        content:'怎么就没人读教程呢？',
                    }
        },
        'lyz_guanyu':{
                    'lyzhongzheng':{
                        order:1,
                        content:'①又一个刀下亡魂！<br>②忠义当先，有进无退！',
                    },
                    'lyzxiansheng':{
                        order:2,
                        content:'①不杀此人，何以雪恨？<br>②还我头来！',
                    },
                    'wushen':{
                        order:3,
                        content:'（默认）',
                    },
                    'die':{
                        content:'夙愿已了，魂归地府……',
                    }
        },
        'lyz_guanyinping':{
                    'lyzrongcheng':{
                        order:1,
                        content:'①还没有结束呢！<br>②欲与父亲一同闯天下！',
                    },
                    'lyzzhuoji':{
                        order:2,
                        content:'①血债累累，你，算得清吗？<br>②就让一切，染上血色吧！',
                    },
                    'die':{
                        content:'不该让仇恨……蒙蔽了双眼……',
                    }
        },
        'lyz_xunyu':{
                    'lyzwangzuo':{
                        order:1,
                        content:'①以王佐之才，驱匹夫之勇。<br>②七尺之身，既已许国，难再许公。',
                    },
                    'lyzxianshi':{
                        order:2,
                        content:'①静待良机，一击灭敌！<br>②不战而屈敌之兵。',
                    },
                    'lyzxiaoran':{
                        order:3,
                        content:'①谢主隆恩……',
                    },
                    'lyznewkunfen':{
                        order:4,
                        content:'①或忠信而死节兮，或訑谩而不疑。<br>②生食汉禄，死为汉臣。',
                    },
                    'die':{
                        content:'捐躯秉汉节，一死何足惜。',
                    }
        },
        'lyz_zhangliao':{
                    'lyzliaolai':{
                        order:1,
                        content:'①十万围困，吾亦能破袭擒贼！<br>②突袭速攻，形如闪电！',
                    },
                    'lyzshepo':{
                        order:2,
                        content:'①煞敌士气，安定军心。<br>②突出险招，直取敌命！',
                    },
                    'die':{
                        content:'感丞相大恩，此生可了……',
                    }
        },
        'lyz_xinxianying':{
                    'lyztaoming':{
                        order:1,
                        content:'①管中可窥豹，一叶而知秋。<br>②此人肆意放纵，必有异志！',
                    },
                    'lyzcaiqing':{
                        order:2,
                        content:'①谁说女子无才便是德？<br>②小女才疏学浅，将军见笑。',
                    },
                    'die':{
                        content:'看错你，竟是万劫不复。',
                    }
        },
        'lyz_shijian':{
                    'lyzpianwu':{
                        order:1,
                        content:'①慈航化众生，司南引轩辕。<br>②天上九宫十二城，仙云袅袅授长生。<br>③宝体天赐，触之必溃。<br>④碧霄一鹤引霞至，玄女箜篌九天来。',
                    },
                    'die':{
                        content:'世间何来两全法，不负仙律不负卿。',
                    }
        },
        'lyz_lvlingqi':{
                    'lyzzhanmo':{
                        order:1,
                        content:'①我乃温侯吕奉先之女。<br>②继父神威，无坚不摧！',
                    },
                    'lyzyoulin':{
                        order:2,
                        content:'①方天映黛眉，赤兔牵红妆。<br>②武姬青丝利，巾帼女儿红。',
                    },
                    'die':{
                        content:'父亲，女儿好累……',
                    }
        },
        'lyz_zuoci':{
                    'lyzchenju':{
                        order:1,
                        content:'①为仙之道，缥缈莫测。<br>②仙人之力，昭于世间。',
                    },
                    'lyzchuiweng':{
                        order:2,
                        content:'①天之正者，不可逆之，逆之，虽盛必衰矣。<br>②幻化之术警之，为政者自当为国为民。',
                    },
                    'lyzwangsheng':{
                        order:3,
                        content:'①吾多与天地精神之往来，生即死，死又复生。<br>②傍日月，携宇宙，游乎尘垢之外。',
                    },
                    'die':{
                        content:'万事，皆有因果。',
                    }
        },
        'lyz_jiaxu':{
                    'lyzjiansha':{
                        order:1,
                        content:'①施经布略由我，剩下的任由将军。<br>②兵以诈立，不如，任其来攻。',
                    },
                    'lyzyinlan':{
                        order:2,
                        content:'①汝等若心存隐忍，顷刻便尸骨无存！<br>②在下所谋之法，唯恐天下不乱！',
                    },
                    'lyzminwei':{
                        order:3,
                        content:'①我自冷眼看世界，不问天下是与非。<br>②你们的技俩，动不了我一根寒毛。',
                    },
                    'die':{
                        content:'终究没能在乱世……善终……',
                    }
        },
        'lyz_sunce':{
                    'lyzaolie':{
                        order:1,
                        content:'①吾等勠力同心，定能回天转日！<br>②建功立业、封妻荫子，正其时也！',
                    },
                    'lyzdingjiang':{
                        order:2,
                        content:'①大丈夫行于世，自当志在天下四方！<br>②父兵诛卓起长沙，直取江东做帝家！',
                    },
                    'lyzbalve':{
                        order:3,
                        content:'①卿等且去讨贼，快去快回！',
                    },
                    'yingba':{
                        order:4,
                        content:'（默认）',
                    },
                    'lyztianyi':{
                        order:5,
                        content:'①大军横扫之处，无不臣服！',
                    },
                    'lyzyingzi':{
                        order:6,
                        content:'①驰骋疆场，快哉，快哉！',
                    },
                    'lyzpojun':{
                        order:7,
                        content:'①所当者破，所击者服！',
                    },
                    'lyzpoxi':{
                        order:8,
                        content:'①孙家天下孙家兵，成就千秋万世名！',
                    },
                    'lyzyinghun':{
                        order:9,
                        content:'①列祖列宗，赐我力量，保我大吴！',
                    },
                    'die':{
                        content:'一世英名，付诸东流……',
                    }
        },
        'lyz_ziyu':{
                    'lyzkezhi':{
                        order:1,
                        content:'①履下如薄冰，浅行尚可止。<br>②无力抗寰宇，寸铁难敌仙。',
                    },
                    'lyzyouxun':{
                        order:2,
                        content:'①自占以诱敌，以徇其功名。<br>②循循且相诱，天象以克之！',
                    },
                    'die':{
                        content:'吾本难胜天，可竟也胜不了你。',
                    }
        },
        'lyz_xusheng':{
                    'lyzyinjun':{
                        order:1,
                        content:'①若敢来犯，必叫你大败而归！<br>②犯大吴疆土者，盛必击而破之！',
                    },
                    'lyzmingbu':{
                        order:2,
                        content:'①以攻为守，破敌卫疆。<br>②这长江天险后，便是江东铁壁！',
                    },
                    'die':{
                        content:'盛之恨，不能再为主公破敌制胜啦……',
                    }
        },
        'lyz_bulianshi':{
                    'lyzxinlan':{
                        order:1,
                        content:'①心虽止矣，思君不停。<br>②今夕往矣，留待成忆。',
                    },
                    'lyzyanzun':{
                        order:2,
                        content:'①援以济困，助以心安。<br>②安魂定心，体恤善慰。',
                    },
                    'die':{
                        content:'初心不忘，来世再续。',
                    }
        },
       'lyz_xuedaoshaozhu':{
                    'lyzyintian':{
                        order:1,
                        content:'①放眼天下，唯我仇海独游！<br>②仇恨让人清醒，来吧！',
                    },
                    'lyzyudi':{
                        order:2,
                        content:'①天地不仁，当视苍生为刍狗。<br>②来来来，且试吾颈硬否？',
                    },
                    'lyzdianshen':{
                        order:3,
                        content:'①仇海翻波，又能奈我何？哈哈哈哈哈哈。<br>②肆意而行，快哉快哉！',
                    },
                    'lyzrugui':{
                        order:4,
                        content:'①不发狂，就灭亡！<br>②众人与蝼蚁何异？哈哈哈。',
                    },
                    'die':{
                        content:'我死后，管他洪水滔天。',
                    }
        },
        'lyz_shen_zhenji':{
                    'lyzqiqing':{
                        order:1,
                        content:'①画堂芳菲梦，琼酿玉衣怜。<br>②玉箸凝腮，姿貌绝伦。',
                    },
                    'lyzshenjiang':{
                        order:2,
                        content:'①河洛之神，诗赋可抒。<br>②云神鱼游，罗扇掩面。',
                    },
                    'lyzdianchuan':{
                        order:3,
                        content:'①洛水起涟漪，粉彩点绛唇。<br>②清尘洛川水，神女踏波游。',
                    },
                    'die':{
                        content:'众口铄金，难证吾清。',
                    }
        },
        'lyz_shen_zhugeliang':{
                    'lyzdouzhuan':{
                        order:1,
                        content:'①斗转星移，七星借命！<br>②伏望天恩，誓讨汉贼！',
                    },
                    'lyzxingsuo':{
                        order:2,
                        content:'①七星八阵，敌军将困。<br>②七星不灭，法力不绝。',
                    },
                    'lyztianji':{
                        order:3,
                        content:'①主灯未灭，我便不息。<br>②星象为我控，七星握掌中！',
                    },
                    'die':{
                        content:'时也，命也……',
                    }
        },
        'lyz_nanxun':{
                    'lyzdingzheng':{
                        order:1,
                        content:'（暂无）',
                    },
                    'lyzshiyi':{
                        order:2,
                        content:'（暂无）',
                    },
                    'lyzhuanxing':{
                        order:3,
                        content:'（暂无）',
                    },
                    'die':{
                        content:'（暂无）',
                    }
        },
        'lyz_shen_guanyu':{
                    'lyzmingjue':{
                        order:1,
                        content:'①汝以奸计害吾，吾定当报还。<br>②向死而生，贼仇必报！',
                    },
                    'lyzyanren':{
                        order:2,
                        content:'①鬼龙斩月刀！<br>②千里追魂，一刀索命！',
                    },
                    'lyzedao':{
                        order:3,
                        content:'①生当啖汝之肉！<br>②死当追汝之魂！',
                    },
                    'die':{
                        content:'忠魂索命，无远弗届……',
                    }
        },
        'lyz_wangyi':{
                    'lyzzhaojie':{
                        order:1,
                        content:'①忠贞与国，节烈与身。<br>②我辈虽女流，烈胆胜须眉！',
                    },
                    'lyzyingwu':{
                        order:2,
                        content:'①孤城临险，须出奇计。<br>②秘计九出，佐君平贼。',
                    },
                    'die':{
                        content:'吾死不足怜惜，无奈家仇未报！',
                    }
        },
    
    
    };
    lib.qhlypkg.push({
        isExt:true,//是否是扩展，一般填true
        filterCharacter:function(name){
            return name.indexOf('lyz_') == 0;//判断此ID的武将是否属于此皮肤包
        },
        skillSkin:function(name,skin,skill){
            var extSkin = {
                'lyz_shen_lvbu':{
                    '___origin':{
                        'lyznuozhan':1,//恢复皮肤初始状态
                        'lyzxiaohu':1,//恢复皮肤初始状态
                        'lyzzhenguan':lib.config.ygbLutou==false?['extension/阳光包/image/character/lyz_shen_lvbu2.jpg','extension/阳光包/image/character/lyz_shen_lvbu3.jpg']:['extension/阳光包/image/lutou/lyz_shen_lvbu2.jpg','extension/阳光包/image/lutou/lyz_shen_lvbu3.jpg'], 
                    },
                },
                'lyz_liubei':{
                    '___origin':{
                        'lyzzhaoren':1,//恢复皮肤初始状态
                        'lyzlongjie':lib.config.ygbLutou==false?'extension/阳光包/image/character/lyz_liubei2.jpg':'extension/阳光包/image/lutou/lyz_liubei2.jpg', 
                    },
                    'lyz_liubeip1.jpg':{
                        'lyzzhaoren':1,//恢复皮肤初始状态
                        'lyzlongjie':lib.config.ygbLutou==false?'extension/阳光包/image/character/lyz_liubei2.jpg':'extension/阳光包/image/lutou/lyz_liubei2.jpg', 
                    },
                },
                'lyz_guanyu':{
                    '___origin':{
                        'lyzhongzheng':1,//恢复皮肤初始状态
                        'lyzxiansheng':lib.config.ygbLutou==false?'extension/阳光包/image/character/lyz_guanyu2.jpg':'extension/阳光包/image/lutou/lyz_guanyu2.jpg', 
                    },
                    'lyz_guanyup1.jpg':{
                        'lyzhongzheng':1,//恢复皮肤初始状态
                        'lyzxiansheng':lib.config.ygbLutou==false?'extension/阳光包/image/character/lyz_guanyu2.jpg':'extension/阳光包/image/lutou/lyz_guanyu2.jpg', 
                    }
                },
                'lyz_xunyu':{
                    '___origin':{
                        'lyzwangzuo':1,//恢复皮肤初始状态
                        'lyzxiaoran':lib.config.ygbLutou==false?'extension/阳光包/image/character/lyz_xunyu2.jpg':'extension/阳光包/image/lutou/lyz_xunyu2.jpg', 
                    },
                },
                'lyz_sunce':{
                    '___origin':{
                        'lyzaolie':1,//恢复皮肤初始状态
                        'lyzdingjiang':lib.config.ygbLutou==false?['extension/阳光包/image/character/lyz_sunce2.jpg','extension/阳光包/image/character/lyz_sunce3.jpg']:['extension/阳光包/image/lutou/lyz_sunce2.jpg','extension/阳光包/image/lutou/lyz_sunce3.jpg'], 
                    },
                },

            };
            var info = extSkin[name];
            if(info){
                var info2 = info[skin ? skin:'___origin'];
                if(info2){
                    return info2[skill];
                }
            }
            return undefined;
        },
        characterNameTranslate:function(name){
            //这里根据武将ID返回其中文名字。
            return get.translation(name);
        },
        characterTaici:function(name){
            //这里返回武将原皮台词。
            return taici[name];
        },
        originSkinInfo:function(name){
            var info = {
                'lyz_zhaoyun':'',
                'lyz_shen_diaochan':'',
                'lyz_shen_zhangliao':'',
                'lyz_shen_gaodayihao':'',
                'lyz_zhugeliang':'',
                'lyz_mayunlu':'',
                'lyz_zhouyu':'',
                'lyz_shen_lvbu':'',
                'lyz_lingju':'',
                'lyz_caiwenji':'',
                'lyz_zhenji':'',
                'lyz_daqiao':'',
                'lyz_xiaoqiao':'',
                'lyz_sunshangxiang':'',
                'lyz_huangyueying':'',
                'lyz_simayi':'',
                'lyz_guojia':'',
                'lyz_machao':'',
                'lyz_hatuo':'',
                'lyz_caojie':'',
                'lyz_caocao':'',
                'lyz_liubei':'',
                'lyz_sunjian':'',
                'lyz_zhangjiao':'',
                'lyz_zhangchunhua':'',
                'lyz_luxun':'',
                'lyz_shen_simayi':'',
                'lyz_zhangxingcai':'',
                'lyz_diaochan':'',
                'lyz_shen_zhouyu':'',
                'lyz_yangguangweiliang':'',
                'lyz_zhangfei':'',
                'lyz_yjlgt':'技能审核及武将配音：遗计两个桃<br>本配音独家授权“阳光包”，禁止未经作者允许以任何形式转载、编辑、盗取此配音用作任何其他用途。',
                'lyz_guanyu':'',
                'lyz_guanyinping':'',
                'lyz_xunyu':'',
                'lyz_zhangliao':'',
                'lyz_xinxianying':'',
                'lyz_shijian':'技能设计及代码编写：诗笺',
                'lyz_lvlingqi':'',
                'lyz_zuoci':'',
                'lyz_jiaxu':'',
                'lyz_sunce':'',
                'lyz_ziyu':'技能审核及武将配音：周子鱼yu<br>本配音独家授权“阳光包”，禁止未经作者允许以任何形式转载、编辑、盗取此配音用作任何其他用途。',
                'lyz_xusheng':'',
                'lyz_bulianshi':'',
                'lyz_xuedaoshaozhu':'技能设计及配音筛选：血刀少主',
                'lyz_shen_zhenji':'',
                'lyz_shen_zhugeliang':'',
                'lyz_nanxun':'技能思路及素材提供：尋',
                'lyz_shen_guanyu':'',
                'lyz_wangyi':'',
            
            };
            return info[name];
        },
        characterInfo:function(name){
            //这里可以返回角色资料。如不返回则显示get.characterIntro(name)。
        },
        prefix:'extension/阳光包/image/character/', //原皮前缀，标识原皮肤的位置。     
        lutouPrefix:'extension/阳光包/image/lutou/',
        isLutou:lib.config.ygbLutou,   
        skin:{
            standard:'extension/阳光包/skin/standard/',//可切换普通皮肤的前缀
            lutou:'extension/阳光包/skin/lutou/',
        },
        audioOrigin:'extension/阳光包/audio/',//原技能配音位置
        audio:'extension/阳光包/skin/audio/',//切换皮肤后的技能配音位置
        skininfo:{
        //皮肤台词
            'lyz_zhaoyunp1':{
				level:"传说",
				translation:"赤胆龙心",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzlongying':{
                        order:1,
                        content:'①豪胆干云立乾坤，枪出寒潭斩蛟龙！<br>②剑起星奔诛万里，摧却终南第一峰！',
                    },
                    'lyzhunyou':{
                        order:2,
                        content:'①枪出如龙势如虎，气掠涯南海角东！<br>②天涯海角不相负，海角天涯豪气存！',
                    },
                    'lyzcuizhen':{
                        order:3,
                        content:'①无知小儿，先站稳阵脚再来吧！<br>②是谁给你的勇气，来跟本将军叫阵！',
                    },
                    'lyzchengyu':{
                        order:4,
                        content:'①一人一枪一匹马，疆场尽驰骋！<br>②龙升九天，马踏飞燕！',
                    },
                    'die':{
                        content:'红日坠瑶池，白袍入枯冢。',
                    }
                }
            },
            'lyz_shen_gaodayihaop1':{
				level:"史诗",
				translation:"孤胆救主",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzjuejing':{
                        order:1,
                        content:'①龙战于野，其血玄黄！',
                    },
                    'lyzlonghun':{
                        order:2,
                        content:'①千里一怒，红莲灿世！<br>②腾龙行云，首尾不见。<br>③潜龙于渊，摄灵愈伤。<br>④金甲映日，驱邪去秽！',
                    },
                    'lyzzhanjiang':{
                        order:3,
                        content:'①龙战于野，其血玄黄！',
                    },
                    'die':{
                        content:'血染鳞甲，龙坠九天……',
                    }
                }
            },         
            'lyz_zhugeliangp1':{
				level:"传说",
				translation:"明良千古",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzwendao':{
                        order:1,
                        content:'①披星戴月，力启洪荒。<br>②天衍四九，人遁其一。',
                    },
                    'lyzzhaoce':{
                        order:2,
                        content:'①空城一曲古琴调，管教天下英豪惊！<br>②如此虚虚实实之法，方能以少胜多。',
                    },
                    'lyzkuitian':{
                        order:3,
                        content:'①唉，天意终不可违……<br>②汉祚将兴，便在此役而成！',
                    },
                    'die':{
                        content:'臣一生所为，无非鞠躬尽瘁，死而后已！',
                    }
                }
            }, 
            'lyz_zhugeliangp2':{
				level:"传说",
				translation:"一枕清梦",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzwendao':{
                        order:1,
                        content:'①披星戴月，力启洪荒。<br>②天衍四九，人遁其一。',
                    },
                    'lyzzhaoce':{
                        order:2,
                        content:'①君子坦荡荡，岂立危墙下。<br>②老夫独守此城，何惧万马千军！',
                    },
                    'lyzkuitian':{
                        order:3,
                        content:'①半生韶华付社稷，一枕清梦压星河。<br>②繁星四百八十万，颗颗鉴照老臣心。',
                    },
                    'die':{
                        content:'独木难支益州地，上方雨落万事空。',
                    }
                }
            },
            'lyz_mayunlup1':{
				level:"普通",
				translation:"为父伤怀",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①贼人，是不是被本姑娘给吓破胆了呀？<br>②看我不好好杀杀你的威风！',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'子龙哥哥，救我！',
                    }
                }
            },
            'lyz_mayunlup2':{
				level:"精品",
				translation:"念君何归",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①哼，就凭你也想跟本姑娘比试？<br>②哈哈，都怪我实力太强了。',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'不算不算，改日再战！',
                    }
                }
            },
            'lyz_mayunlup3':{
				level:"史诗",
				translation:"枪舞乾坤",
				info:"",
                order:3,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①贼人，是不是被本姑娘给吓破胆了呀？<br>②看我不好好杀杀你的威风！',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'子龙哥哥，救我！',
                    }
                }
            },
            'lyz_mayunlup4':{
				level:"传说",
				translation:"花海舞枪",
				info:"",
                order:4,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①西凉铁骑，北地枪法，你如何能挡？<br>②骏马银枪，敌莫敢当。',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'子龙，大哥，来世再会……',
                    }
                }
            },
            'lyz_mayunlup5':{
				level:"传说",
				translation:"烟绚繁星",
				info:"",
                order:5,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①将门之女，有何畏惧可言？<br>②知晓敌情，取胜，何难之有？',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'想不到，我也有父兄们那一天。',
                    }
                }
            },
            'lyz_mayunlup6':{
				level:"限定",
				translation:"花好月圆",
				info:"",
                order:6,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①看我一击必中要害！<br>②定拿你项上人头，为我夫君助阵。',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'怪我武艺不精，难报父仇……',
                    }
                }
            },
            'lyz_mayunlup7':{
				level:"限定",
				translation:"巾帼花武",
				info:"",
                order:7,//显示顺序，号越小越前面。
                skill:{
                    'lyzjingxing':{
                        order:1,
                        content:'①飞花鎏金，凤仪枪武。<br>②凤栖梧桐，吾归沙场。',
                    },
                    'lyzfengyi':{
                        order:2,
                        content:'①战场上，看你耍什么花样！<br>②这些小兵，我来对付足矣。',
                    },
                    'lyzlingxiang':{
                        order:3,
                        content:'①贼人，是不是被本姑娘给吓破胆了呀？<br>②看我不好好杀杀你的威风！',
                    },
                    'fanghun_lyz_mayunlu':{
                        order:4,
                        content:'①小小鼠辈，还不配与我夫君过招！',
                    },
                    'tieqi_lyz_mayunlu':{
                        order:5,
                        content:'①连我都打不过，还想挑战我哥？',
                    },
                    'die':{
                        content:'寂寂花语多，相思谁来解……',
                    }
                }
            },
            'lyz_lingjup1':{
				level:"传说",
				translation:"骐舞凤歌",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzwuren':{
                        order:1,
                        content:'①隐忍多时，就为了这一日。<br>②复仇的滋味，是如此甜美。',
                    },
                    'lyzhongshang':{
                        order:2,
                        content:'①过去的一切，都与我无关了。<br>②从今天起，只为自己而活。',
                    },
                    'die':{
                        content:'此生，犹如梦境一般……',
                    }
                }
            },
            'lyz_caiwenjip1':{
				level:"限定",
				translation:"战场绝版",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzchengxin':{
                        order:1,
                        content:'①陈情以白，欲表同心。<br>②乡人相遇，安得不叙旧情？',
                    },
                    'lyzfuqing':{
                        order:2,
                        content:'①凡所经履，莫不暗记。<br>②默而识之，学而不厌。',
                    },
                    'die':{
                        content:'感伤乱离，追怀悲愤……',
                    }
                }
            },
            'lyz_zhenjip1':{
				level:"史诗",
				translation:"牛年清明",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzshenhuang':{
                        order:1,
                        content:'①雨霏兮烟树，雪霏霏兮如霜。<br>②水溢兮芳馨，似杜蘅兮芳蓼。',
                    },
                    'lyzjinghong':{
                        order:2,
                        content:'①掷樽兮离殇，酹杜康兮琼浆。<br>②星辰渐兮忽黯，何失色兮故叟。',
                    },
                    'die':{
                        content:'风袅袅兮暮渺渺，余怅逝兮莫言。',
                    }
                }
            },
            'lyz_zhenjip2':{
				level:"传说",
				translation:"洛神御水",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzshenhuang':{
                        order:1,
                        content:'①采明珠，拾翠羽。<br>②灼若芙蕖出渌波，皎若皓月挂云间。',
                    },
                    'lyzjinghong':{
                        order:2,
                        content:'①华容婀娜，笑颜花绽。<br>②芙蓉不及伊人颜，洛神姗姗珠翠香。',
                    },
                    'die':{
                        content:'洛水点绛萧萧雨……',
                    }
                }
            },
            'lyz_zhenjip3':{
				level:"限定",
				translation:"才颜双绝",
				info:"",
                order:3,//显示顺序，号越小越前面。
                skill:{
                    'lyzshenhuang':{
                        order:1,
                        content:'①洛灵感焉，徙倚彷徨。<br>②虽潜处于太阴，长寄心于君王。',
                    },
                    'lyzjinghong':{
                        order:2,
                        content:'①浮长川而忘返，思绵绵而增慕。<br>②奇服旷世，骨像应图。',
                    },
                    'die':{
                        content:'超长吟以永慕兮，声哀厉而弥长。',
                    }
                }
            },
            'lyz_zhenjip4':{
				level:"限定",
				translation:"端瑞洛水",
				info:"",
                order:4,//显示顺序，号越小越前面。
                skill:{
                    'lyzshenhuang':{
                        order:1,
                        content:'①腾文鱼以警乘，鸣玉鸾以偕逝。<br>②六龙俨其齐首，载云车之容裔。',
                    },
                    'lyzjinghong':{
                        order:2,
                        content:'①柔情绰态，媚于语言。<br>②或戏清流，或翔神渚。',
                    },
                    'die':{
                        content:'遗情想像，顾望怀愁。',
                    }
                }
            },
            'lyz_daqiaop1':{
				level:"史诗",
				translation:"白鹤梁神女",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzyurong':{
                        order:1,
                        content:'①此生容颜，只为君留。<br>②古玉沁色，羞颜暖心。',
                    },
                    'lyzfuhua':{
                        order:2,
                        content:'①丽光耀八溪，玉流通九曲。<br>②流逸飘然，罗裳依依。',
                    },
                    'die':{
                        content:'最苦，便是与将军分别......',
                    }
                }
            },
            'lyz_daqiaop2':{
				level:"传说",
				translation:"衣垂绿川",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzyurong':{
                        order:1,
                        content:'①溪边坐流水，与君共清欢。<br>②衣带逐水去，绿川盼君留。',
                    },
                    'lyzfuhua':{
                        order:2,
                        content:'①此生逢伯符，足以慰平生。<br>②所幸遇郎君，流离得良人。',
                    },
                    'die':{
                        content:'忆君如流水，日夜无歇时。',
                    }
                }
            },
            'lyz_xiaoqiaop1':{
				level:"传说",
				translation:"采莲江南",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzfangze':{
                        order:1,
                        content:'①眉眼盈盈处，芙蕖夭夭时。<br>②千娇映水，细袖嵌香。',
                    },
                    'lyzfumeng':{
                        order:2,
                        content:'①桃花随风逝，飘落待归期。<br>②昨日繁花盛，今日萧萧落。',
                    },
                    'die':{
                        content:'红消香断有谁怜……',
                    }
                }
            },
            'lyz_sunshangxiangp1':{
				level:"普通",
				translation:"手杀爆料",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzbeiwu':{
                        order:1,
                        content:'①爱似鸳鸯戏水，情比蝴蝶双飞。<br>②凝眸柔柔情切切，此缘深深莫匆匆。',
                    },
                    'lyzjiaogong':{
                        order:2,
                        content:'①刀行厚重，剑走轻灵，本小姐皆可用之。<br>②鼓三尺之莹莹，云间闪电，掌上生风。',
                    },
                    'die':{
                        content:'夫君，妾身来陪你了……',
                    }
                }
            },
            'lyz_sunshangxiangp2':{
				level:"传说",
				translation:"箭扫荆棘",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzbeiwu':{
                        order:1,
                        content:'①彩袖双剑鸾凤鸣，良缘牵线醉黛眉。<br>②地生连理枝，水出并头莲。',
                    },
                    'lyzjiaogong':{
                        order:2,
                        content:'①花间皎洁，快步无影。<br>②体态轻盈，出招无形。',
                    },
                    'die':{
                        content:'四水楚歌起，望乡泪满裳。',
                    }
                }
            },
            'lyz_sunshangxiangp3':{
				level:"限定",
				translation:"英俏佳颜",
				info:"",
                order:3,//显示顺序，号越小越前面。
                skill:{
                    'lyzbeiwu':{
                        order:1,
                        content:'①举案齐眉，双剑共引。<br>②夫君，有你在身边真好～',
                    },
                    'lyzjiaogong':{
                        order:2,
                        content:'①弓腰武美姬，巾帼不输君。<br>②本小姐这身本事，可不是假的～',
                    },
                    'die':{
                        content:'江南流水归海心，我愿随水佑吴盛。',
                    }
                }
            },
            'lyz_huangyueyingp1':{
				level:"传说",
				translation:"明良千古",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhiying':{
                        order:1,
                        content:'①奇思机上巧，妙想晦下明。<br>②愚，固曾有，智，从未绝。',
                    },
                    'lyzjinxin':{
                        order:2,
                        content:'①一器一物，皆不可便宜敌军！<br>②吾手中之械，只可为我军所用！',
                    },
                    'die':{
                        content:'夫君尽忠节，妾身亦如是……',
                    }
                }
            },
            'lyz_caojiep1':{
				level:"传说",
				translation:"丹心佑汉",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzxianmu':{
                        order:1,
                        content:'①安民济物，致君己任。<br>②恩泽百姓，国利民福。',
                    },
                    'lyzfengjun':{
                        order:2,
                        content:'①哥哥，你怎可做大逆不道之事！<br>②你们休想拿走玉玺！',
                    },
                    'die':{
                        content:'夫君，臣妾辜负你的期望了。',
                    }
                }
            },
            'lyz_caojiep2':{
				level:"限定",
				translation:"凤历迎春",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzxianmu':{
                        order:1,
                        content:'①施医惠民，以迎元春。<br>②元旦佳节，惠普天下。',
                    },
                    'lyzfengjun':{
                        order:2,
                        content:'①哀家在此，岂由汝等放肆！<br>②天授玺绶，人力岂可夺之！',
                    },
                    'die':{
                        content:'身亡灯灭，俱成空矣。',
                    }
                }
            },
            'lyz_liubeip1':{
				level:"传说",
				translation:"明良千古",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhaoren':{
                        order:1,
                        content:'①仁心民望，威著四海！<br>②以德服人，远胜千军之力！',
                    },
                    'lyzlongjie':{
                        order:2,
                        content:'①怒伤心肝，也阻止不了这复仇之火！<br>②灼艾分痛失，虽万劫，亦杀之！',
                    },
                    'die':{
                        content:'众卿，朕不能一一嘱托，愿皆……自爱。',
                    }
                }
            },
            'lyz_shen_simayip1':{
				level:"传说",
				translation:"鉴往知来",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzchouyi':{
                        order:1,
                        content:'①因果有律，世间无常。<br>②万物无异，强弱有别。',
                    },
                    'lyztianqian':{
                        order:2,
                        content:'①轻举妄为，徒招横祸。',
                    },
                    'lyzdikun':{
                        order:3,
                        content:'①逆势而为，不自量力。',
                    },
                    'lyzguiyuan':{
                        order:4,
                        content:'①吾之身前，万籁俱寂。<br>②吾之身后，了无生机！',
                    },
                    'die':{
                        content:'生门一闭，唯有赴死……',
                    }
                }
            },
            'lyz_zhangchunhuap1':{
				level:"普通",
				translation:"手杀爆料",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzcanqing':{
                        order:1,
                        content:'①多情自古空余恨。<br>②无情不似多情苦。',
                    },
                    'lyzwanai':{
                        order:2,
                        content:'①心虽谅解，隔膜难消。<br>②伤虽痊愈，疤却永存。',
                    },
                    'die':{
                        content:'春恨秋悲皆自惹，为谁欢喜为谁妍。',
                    }
                }
            },
            'lyz_zhangchunhuap2':{
				level:"传说",
				translation:"宣穆夜袭",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzcanqing':{
                        order:1,
                        content:'①杀之以灭口，不留祸患。<br>②你若不死，必为后患！',
                    },
                    'lyzwanai':{
                        order:2,
                        content:'①落花有意，流水无情。<br>②伤天之多变，逝人之多悲。',
                    },
                    'die':{
                        content:'情已怨尽，伤已成恨。',
                    }
                }
            },
            'lyz_zhangchunhuap3':{
				level:"限定",
				translation:"巾帼花武",
				info:"",
                order:3,//显示顺序，号越小越前面。
                skill:{
                    'lyzcanqing':{
                        order:1,
                        content:'①繁星映月满欢喜，悲欢离合总无情。<br>②劝君多珍重，此间不相见。',
                    },
                    'lyzwanai':{
                        order:2,
                        content:'①一缕冷香远，逝花落，笑靥消。<br>②何处蓝染玫色起，伤尽三千痴缠意。',
                    },
                    'die':{
                        content:'孤影自怜，无限愁寒。',
                    }
                }
            },
            'lyz_zhangxingcaip1':{
				level:"传说",
				translation:"凯旋星花",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzlingying':{
                        order:1,
                        content:'①凭父忠勇，斩尽贼寇！<br>②舍我之力，剿魏国刀枪入库，马放南山，永不进犯我大汉！',
                    },
                    'lyzxingxuan':{
                        order:2,
                        content:'①贤洁知淑，仁惠慈爱。<br>②肩负父亲嘱托，扶皇上，保我大汉！',
                    },
                    'die':{
                        content:'请诸位辅佐阿斗，守护汉室基业。',
                    }
                }
            },
            'lyz_zhangxingcaip2':{
				level:"限定",
				translation:"巾帼花武",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzlingying':{
                        order:1,
                        content:'①挥枪平乱世，彩星绽九霄！<br>②逸彩耀星，枪出花海！',
                    },
                    'lyzxingxuan':{
                        order:2,
                        content:'①淑德贤惠，良才兼备。<br>②贤能清雅，常备不懈。',
                    },
                    'die':{
                        content:'几许情深，寒灯独伤怀。',
                    }
                }
            },
            'lyz_diaochanp1':{
				level:"传说",
				translation:"红颜绮梦",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzyinghuo':{
                        order:1,
                        content:'①雄姿英发，难拒细语缠绵。<br>②英雄盖世，折戟美人之关。',
                    },
                    'lyzxingyun':{
                        order:2,
                        content:'①皎月应惭藏云后，芙蓉垂头蔽叶间。<br>②秀色飒群雄，玉颜压众芳。',
                    },
                    'die':{
                        content:'月晦花亦凋，乱世人安在？',
                    }
                }
            },
            'lyz_guanyup1':{
				level:"传说",
				translation:"狂龙怒战",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzhongzheng':{
                        order:1,
                        content:'①策马冲锋，掩其不备！<br>②兼资文武，雄烈过人！',
                    },
                    'lyzxiansheng':{
                        order:2,
                        content:'①不杀此人，何以雪恨？<br>②还我头来！',
                    },
                    'wushen':{
                        order:3,
                        content:'（默认）',
                    },
                    'die':{
                        content:'夙愿已了，魂归地府……',
                    }
                }
            },
            'lyz_guanyinpingp1':{
				level:"史诗",
				translation:"脱兔悍拒",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzrongcheng':{
                        order:1,
                        content:'①女儿定效死，以保汉室！<br>②收复荆州，就在今日！',
                    },
                    'lyzzhuoji':{
                        order:2,
                        content:'①碧眼贼，交出命来！<br>②荡平东吴，以报父仇！',
                    },
                    'die':{
                        content:'父仇未报，就差一点点......',
                    }
                }
            },
            'lyz_guanyinpingp2':{
				level:"传说",
				translation:"虎女兔娇",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzrongcheng':{
                        order:1,
                        content:'①父亲的武艺，我已掌握大半。<br>②有青龙偃月刀在，小女必胜！',
                    },
                    'lyzzhuoji':{
                        order:2,
                        content:'①就用你的性命，一雪前耻！<br>②雪耻旧恨，今日清算！',
                    },
                    'die':{
                        content:'鸿影花残，此仇未能报......',
                    }
                }
            },
            'lyz_guanyinpingp3':{
				level:"限定",
				translation:"巾帼花武",
				info:"",
                order:3,//显示顺序，号越小越前面。
                skill:{
                    'lyzrongcheng':{
                        order:1,
                        content:'①我的青龙偃月刀，可等待好久了。<br>②武圣之力，我岂会荒废？',
                    },
                    'lyzzhuoji':{
                        order:2,
                        content:'①风雪如寒，也挡不住我恨意之火！<br>②雪漫金银落，花恨流水错。',
                    },
                    'die':{
                        content:'鸟飞兔走，浮生梦散。',
                    }
                }
            },
            'lyz_yjlgtp1':{
				level:"限定",
				translation:"飘颻龙虎衣",
				info:"技能审核及武将配音：遗计两个桃<br>本配音独家授权“阳光包”，禁止未经作者允许以任何形式转载、编辑、盗取此配音用作任何其他用途。",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhidian':{
                        order:1,
                        content:'①《全教程》让你的无名杀生涯如虎添翼。<br>②费了九牛二虎之力才写出来的教程，还不过来看看？',
                    },
                    'lyzshulun':{
                        order:2,
                        content:'①朝避猛虎，夕避长蛇。<br>②朱门拥虎士，列戟何森森。',
                    },
                    'lyzjianji':{
                        order:3,
                        content:'①老虎不发威，你当我是病猫啊？<br>②乳虎啸谷，百兽震惶。',
                    },
                    'die':{
                        content:'真是虎落平阳被犬欺。',
                    }
                }
            },
            'lyz_lvlingqip1':{
				level:"传说",
				translation:"炽焱流金",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhanmo':{
                        order:1,
                        content:'①吕家有女初长成，戟出名扬天下惊。<br>②试问天下武夫，谁配画戟方天？',
                    },
                    'lyzyoulin':{
                        order:2,
                        content:'①古时妇好今时我，红袖弄钺话铿锵。<br>②吕家女儿胜须眉，胭脂红妆配武裳！',
                    },
                    'die':{
                        content:'宁立寒风死，不俯贼巢生！',
                    }
                }
            },
            'lyz_lvlingqip2':{
				level:"传说",
				translation:"繁华彩鸢",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhanmo':{
                        order:1,
                        content:'①穷途末路，亦当死中求活！<br>②势穷力尽，怎能坐以待毙？',
                    },
                    'lyzyoulin':{
                        order:2,
                        content:'①虓女暴怒发冲冠，画戟刃过惊雷断！<br>②纵马执戟冲敌阵，天下谁人敢当锋！',
                    },
                    'die':{
                        content:'戟断马亡，此地竟是我的葬身之处吗？',
                    }
                }
            },
            'lyz_shen_guanyup1':{
				level:"传说",
				translation:"链狱鬼神",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzmingjue':{
                        order:1,
                        content:'①汝以奸计害吾，吾定当报还。<br>②向死而生，贼仇必报！',
                    },
                    'lyzyanren':{
                        order:2,
                        content:'①鬼龙斩月刀！<br>②千里追魂，一刀索命！',
                    },
                    'lyzedao':{
                        order:3,
                        content:'①生当啖汝之肉！<br>②死当追汝之魂！',
                    },
                    'die':{
                        content:'我还会回来的……',
                    }
                }
            },
            'lyz_wangyip1':{
				level:"史诗",
				translation:"轻燕掠影",
				info:"",
                order:1,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhaojie':{
                        order:1,
                        content:'①守义死节，不为苟生。<br>②秉忠持义，纵死犹归。',
                    },
                    'lyzyingwu':{
                        order:2,
                        content:'①奇谋九策，共御强敌。<br>②密谋筹策，奇计制敌。',
                    },
                    'die':{
                        content:'为雪君父之耻，死而不惜！',
                    }
                }
            },
            'lyz_wangyip2':{
				level:"传说",
				translation:"绝色异彩",
				info:"",
                order:2,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhaojie':{
                        order:1,
                        content:'①忠贞与国，节烈与身。<br>②我辈虽女流，烈胆胜须眉！',
                    },
                    'lyzyingwu':{
                        order:2,
                        content:'①孤城临险，须出奇计。<br>②秘计九出，佐君平贼。',
                    },
                    'die':{
                        content:'吾死不足怜惜，无奈家仇未报！',
                    }
                }
            },
            'lyz_wangyip3':{
				level:"传说",
				translation:"心伤花怜",
				info:"",
                order:3,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhaojie':{
                        order:1,
                        content:'①婉娩贞烈，不输兵将。<br>②至柔动刚，贞洁不移。',
                    },
                    'lyzyingwu':{
                        order:2,
                        content:'①共勉卒勋，不可顺逆转之意。<br>②管仲入齐，立九合之功。',
                    },
                    'die':{
                        content:'未能除马超，愧对夫君。',
                    }
                }
            },
            'lyz_wangyip4':{
				level:"限定",
				translation:"花好月圆",
				info:"",
                order:4,//显示顺序，号越小越前面。
                skill:{
                    'lyzzhaojie':{
                        order:1,
                        content:'①贼人，休想碰我一根寒毛！<br>②驾驭山河，死生何惧！',
                    },
                    'lyzyingwu':{
                        order:2,
                        content:'①铤而走险，方解冀城之围！<br>②有勇无谋之辈，可用巧计破之。',
                    },
                    'die':{
                        content:'巾帼之血流尽，终未能平贼……',
                    }
                }
            },

  
        }
    });
});