'use strict';
window.yunjiang_import(function(lib,game,ui,get,ai,_status){
    if(!lib.qhlypkg){
        lib.qhlypkg = [];
    }
    if(!lib.qhly_groupimage){
        lib.qhly_groupimage = {};
    }
    
    if(!lib.qhly_groupcolor){
        lib.qhly_groupcolor = {};
    }

    var taici = {
    };

    var gonglve = {
        'yunyouzi':"<video width='300' height='200' controls autoplay style='width:50%;height:100%;object-fit:fill;'><source src='"+lib.assetURL+"extension/云将/fuli/SP_1.mp4'</video>",
        'yunliubei':"这似乎是某个宝藏拓展的激活码，一位神秘人赠予用来匡扶汉室的资源，但因为分成了三份只能看到其中一段：yunjiang_*******",
        'yunguanyu':"这似乎是某个宝藏拓展的激活码，一位神秘人因见证了桃园结义所赠送，但因为分成了三份只能看到其中一段：********tyjy***",
        'yunzhangfei':"这似乎是某个宝藏拓展的激活码，一位神秘人因感慨复读机无处不在顺手赠送，但因为分成了三份只能看到其中一段：************lgz",
        'yundongzuo':"这似乎是董卓搜刮汉室珍藏的时候发现的某个宝藏拓展激活码，能换取丰厚的奖励：yunjiang_lhzs",
    };    
    lib.qhlypkg.push({
        isExt:true,//是否是扩展，一般填true
        filterCharacter:function(name){
            return lib.characterPack['mode_extension_云将'] && lib.characterPack['mode_extension_云将'][name];//判断此ID的武将是否属于此皮肤包
        },
        characterIntroduceExtra:function(name){
            var arr = [];
            if(gonglve &&gonglve[name]){
                arr.push({name:'彩蛋',func:'characterGonglve'});
            }
            if(arr.length)return arr;
        },
        characterGonglve:function(name){
            return gonglve[name];
        },
        characterNameTranslate:function(name){
            //这里根据武将ID返回其中文名字。
            return get.translation(name);
        },
        characterTaici:function(name){
            //这里返回武将原皮台词。
            return taici[name];
        },
        originSkinInfo:function(name){
            var info = {
               // 'qhfl_yuncaocao':'原皮说明。',
            };
            return info[name];
        },
        characterInfo:function(name){
            //这里可以返回角色资料。如不返回则显示get.characterIntro(name)。
        },
        prefix:'extension/云将/', //原皮前缀，标识原皮肤的位置。
        lutouPrefix:'extension/云将/lutou/',//露头前缀，标识露头原皮肤位置
        isLutou:lib.config.yjLutou,   
        skin:{
            standard:'extension/云将/skin/image/',//可切换普通皮肤的前缀
            lutou:'extension/云将/skin/lutou/',//可以切换露头皮肤的位置
        },
        audioOrigin:'extension/云将/audio/',//原技能配音位置
        audio:'extension/云将/skin/audio/',//切换皮肤后的技能配音位置
        skininfo:{
        },
        forbidEditTaici:true,
        skillSkin:function(name,skin,skill){
            var extSkin = {                
                'yuncaocao':{
                    '___origin':{
                        'yunzongyu':1,//恢复皮肤初始状态
                        'yunzongyu':'extension/云将/yuncaocao1a.jpg',
                    },
                    'yuncaocao4.jpg':{                  
                        'yunzongyu':'extension/云将/yuncaocao4a.jpg',
                    },
                    'yuncaocao5.jpg':{                  
                        'yunzongyu':'extension/云将/yuncaocao5a.jpg',
                    },
                },
                'yuncaoying':{
                    '___origin':{
                        'yunlingren':1,//恢复皮肤初始状态
                        'yunlingren':'extension/云将/yuncaoyinga.jpg',
                    },
                    'yuncaoying1.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying1a.jpg',
                    },                
                    'yuncaoying2.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying2a.jpg',
                    },
                    'yuncaoying3.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying3a.jpg',
                    },
                    'yuncaoying4.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying4a.jpg',
                    },
                    'yuncaoying5.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying5a.jpg',
                    },
                    'yuncaoying7.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying7a.jpg',
                    },
                    'yuncaoying8.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying8a.jpg',
                    },
                    'yuncaoying9.jpg':{                  
                        'yunlingren':'extension/云将/yuncaoying9a.jpg',
                    },
                },
                'yuncaopi':{
                    '___origin':{
                        'yundengwei':1,//恢复皮肤初始状态
                        'yundengwei':'extension/云将/yuncaopi1a.jpg',
                    },
                    'yuncaopi4.jpg':{                  
                        'yundengwei':'extension/云将/yuncaopi4a.jpg',
                    },
                },
                'yunsimayi':{                   
                    'yunsimayi4.jpg':{                  
                        'yunyingshi':'extension/云将/yunsimayi4a.jpg',
                    },
                    'yunsimayi5.jpg':{                  
                        'yunyingshi':'extension/云将/yunsimayi5a.jpg',
                    },
                },
                'yunzhangchunhua':{
                    '___origin':{
                        'yunjuekou':1,//恢复皮肤初始状态
                        'yunjuekou':'extension/云将/yunzhangchunhua1a.jpg',
                    },
                    'yunzhangchunhua4.jpg':{                  
                        'yunjuekou':'extension/云将/yunzhangchunhua4a.jpg',
                    },
                    'yunzhangchunhua5.jpg':{                  
                        'yunjuekou':'extension/云将/yunzhangchunhua5a.jpg',
                    },                    
                    'yunzhangchunhua8.jpg':{                  
                        'yunjuekou':'extension/云将/yunzhangchunhua8a.jpg',
                    },
                },
                'yunguanyu':{
                    'yunguanyu4.jpg':{
                        'yunguayin':1,//恢复皮肤初始状态
                        'yunguayin':'extension/云将/yunguanyu4a.jpg',
                    },                    
                },
                'yunhuangyueying':{
                    '___origin':{
                        'yunqiqiao':1,//恢复皮肤初始状态
                        'yunqiqiao':'extension/云将/yunhuangyueying1a.jpg',
                    },    
                    'yunhuangyueying5.jpg':{
                        'yunqiqiao':1,//恢复皮肤初始状态
                        'yunqiqiao':'extension/云将/yunhuangyueying5a.jpg',
                    },     
                    'yunhuangyueying5.1.jpg':{
                        'yunqiqiao':1,//恢复皮肤初始状态
                        'yunqiqiao':'extension/云将/yunhuangyueying5.1a.jpg',
                    },               
                },
                'yunliubei':{
                    '___origin':{
                        'yunsangu':1,//恢复皮肤初始状态
                        'yunsangu':'extension/云将/yunliubei1a.jpg',
                    },                    
                },
                'yunpangtong':{
                    '___origin':{
                        'yunfengming':1,//恢复皮肤初始状态
                        'yunfengming':'extension/云将/yunpangtong1a.jpg',
                    },                    
                    'yunpangtong5.jpg':{
                        'yunfengming':1,//恢复皮肤初始状态
                        'yunfengming':'extension/云将/yunpangtong5a.jpg',
                    },                   
                },
                'yunsunce':{
                    '___origin':{
                        'yunxianxi':1,//恢复皮肤初始状态
                        'yunxianxi':'extension/云将/yunsunce1a.jpg',
                    },                    
                },
                'yunsunquan':{
                    '___origin':{
                        'yunjianye':1,//恢复皮肤初始状态
                        'yunjianye':'extension/云将/yunsunquan1a.jpg',
                    },                    
                },
                'yunxushi':{
                    '___origin':{
                        'yunfuzhu':1,//恢复皮肤初始状态
                        'yunfuzhu':'extension/云将/yunxushi1a.jpg',
                    },                    
                },
                'yunzhouyu':{
                    '___origin':{
                        'yunyeyan':1,//恢复皮肤初始状态
                        'yunyeyan':'extension/云将/yunzhouyu1a.jpg',
                    },   
                    'yunzhouyu5.jpg':{
                        'yunyeyan':1,//恢复皮肤初始状态
                        'yunyeyan':'extension/云将/yunzhouyu5a.jpg',
                    },                                    
                },
                'yuncaishi':{
                    '___origin':{
                        'yunxianzhou':1,//恢复皮肤初始状态
                        'yunxianzhou':'extension/云将/yuncaishi1a.jpg',
                    },   
                    'yuncaishi4.jpg':{
                        'yunxianzhou':1,//恢复皮肤初始状态
                        'yunxianzhou':'extension/云将/yuncaishi4a.jpg',
                    },                                           
                    'yuncaishi8.jpg':{
                        'yunxianzhou':1,//恢复皮肤初始状态
                        'yunxianzhou':'extension/云将/yuncaishi8a.jpg',
                    },                                               
                },
                'db_yundaxiaoqiao':{
                    '___origin':{
                        'fengyunshibian_dxq':1,//恢复皮肤初始状态
                        'fengyunshibian_dxq':'extension/云将/db_yundaxiaoqiao1a.jpg',
                    },                    
                },
                'yunzhangjiao':{
                    '___origin':{
                        'yunhuangtian':1,//恢复皮肤初始状态
                        'yunhuangtian':'extension/云将/yunzhangjiao1a.jpg',
                    },                    
                    'yunzhangjiao7.jpg':{
                        'yunhuangtian':1,//恢复皮肤初始状态
                        'yunhuangtian':['extension/云将/yunzhangjiao7a.jpg','extension/云将/yunzhangjiao7b.jpg'],
                    },                    
                },
                'yundiaochan':{
                    '___origin':{
                        'yunbiyue':1,//恢复皮肤初始状态
                        'yunbiyue':'extension/云将/yundiaochan1a.jpg',
                    },     
                    'yundiaochan7.jpg':{
                        'yunbiyue':1,//恢复皮肤初始状态
                        'yunbiyue':'extension/云将/yundiaochan7a.jpg',
                    },                                   
                },
                'yundongbai':{
                    '___origin':{
                        'yunjiaoheng':1,//恢复皮肤初始状态
                        'yunjiaoheng':'extension/云将/yundongbai1a.jpg',
                    },     
                    'yundongbai5.jpg':{
                        'yunjiaoheng':1,//恢复皮肤初始状态
                        'yunjiaoheng':'extension/云将/yundongbai5a.jpg',
                    },                                   
                },
                'db_yunjiaxu':{
                    '___origin':{
                        'yunjimou':1,//恢复皮肤初始状态
                        'yunjimou':'extension/云将/db_yunjiaxu1a.jpg',
                    },  
                    'db_yunjiaxu5.jpg':{
                        'yunjimou':1,//恢复皮肤初始状态
                        'yunjimou':'extension/云将/db_yunjiaxu5a.jpg',
                    },                    
                },
                'yunzhaoxiang':{
                    'yunzhaoxiang5.jpg':{
                        'yunfanghun':1,//恢复皮肤初始状态
                        'yunfanghun':'extension/云将/yunzhaoxiang5a.jpg',
                    },                    
                },
                'yunjiangwei':{
                    '___origin':{
                        'yunqilin':1,//恢复皮肤初始状态
                        'yunqilin':['extension/云将/yunjiangwei1a.jpg','extension/云将/yunjiangwei1b.jpg','extension/云将/yunjiangwei1c.jpg'],
                    },
                    'yunjiangwei5.jpg':{
                        'yunqilin':1,//恢复皮肤初始状态
                        'yunqilin':['extension/云将/yunjiangwei5a.jpg','extension/云将/yunjiangwei5b.jpg','extension/云将/yunjiangwei5c.jpg'],
                    },
                },
                'yuncaiwenji':{
                    '___origin':{
                        'yunbeige':1,//恢复皮肤初始状态
                        'yunbeige':['extension/云将/yuncaiwenji1a.jpg','extension/云将/yuncaiwenji1b.jpg','extension/云将/yuncaiwenji1c.jpg'],
                    },                    
                    'yuncaiwenji5.jpg':{
                        'yunbeige':1,//恢复皮肤初始状态
                        'yunbeige':['extension/云将/yuncaiwenji5a.jpg','extension/云将/yuncaiwenji5b.jpg','extension/云将/yuncaiwenji5c.jpg'],
                    },                    
                },
                'yunsunshangxiang':{
                    '___origin':{
                        'yunxiaoji':1,//恢复皮肤初始状态
                        'yunxiaoji':['extension/云将/yunsunshangxiang1a.jpg','extension/云将/yunsunshangxiang1b.jpg','extension/云将/yunsunshangxiang1c.jpg','extension/云将/yunsunshangxiang1d.jpg'],
                    },                    
                    'yunsunshangxiang5.jpg':{
                        'yunxiaoji':1,//恢复皮肤初始状态
                        'yunxiaoji':['extension/云将/yunsunshangxiang5a.jpg','extension/云将/yunsunshangxiang5b.jpg','extension/云将/yunsunshangxiang5c.jpg','extension/云将/yunsunshangxiang5d.jpg'],
                    },                    
                    'yunsunshangxiang9.jpg':{
                        'yunxiaoji':1,//恢复皮肤初始状态
                        'yunxiaoji':['extension/云将/yunsunshangxiang9a.jpg','extension/云将/yunsunshangxiang9b.jpg','extension/云将/yunsunshangxiang9c.jpg','extension/云将/yunsunshangxiang9d.jpg'],
                    },                    
                },
                
            };
            var info = extSkin[name];
            if(info){
                var info2 = info[skin ? skin:'___origin'];
                if(info2){
                    return info2[skill];
                }
            }
            return undefined;
        },
    });
});