'use strict';
window.qhly_import(function(lib,game,ui,get,ai,_status){
    lib.qhly_sanguotaici = {
    
    /*标准*/
    
    //曹操
            'caocao':{
                'jianxiong':{
                    order:1,
                    content:'宁教我负天下人，休教天下人负我！<br>吾好梦中杀人！',
                },
                'hujia':{
                    order:2,
                    content:"魏将何在？<br>来人，护驾！",
                },
                'die':{
                    order:3,
                    content:"霸业未成…未成啊！",
                }
            },
            //郭嘉
            'guojia':{
                'tiandu':{
                    order:1,
                    content:"也好。<br>罢了。",
                },
                'yiji':{
                    order:2,
                    content:'就这样吧~<br>哦？',
                },
                'die':{
                    order:3,
                    content:"咳、咳～～～～"
                }
             },
             //李典
            're_lidian':{
                'xunxun':{
                    order:1,
                    content:"众将死战，非我之功。<br>爱兵如子，胜乃可全。",
                },
                'wangxi':{
                    order:2,
                    content:'大丈夫，何拘小节？<br>前尘往事，莫再提起。',
                },
                'die':{
                    order:3,
                    content:"报国杀敌，虽死犹荣。"
                }
             },
             //司马懿
            'simayi':{
                'fankui':{
                    order:1,
                    content:"下次注意点！ <br>出来混，早晚要还的！",
                },
                'guicai':{
                    order:2,
                    content:'天命？哈哈哈哈～ <br>吾乃天命之子！',
                },
                'die':{
                    order:3,
                    content:"难道真的是天命难违？"
                }
             },
             //夏侯惇
            'xiahoudun':{
                'ganglie':{
                    order:1,
                    content:"鼠辈，竟敢伤我！<br>以彼之道，还施彼身！",
                },
                'die':{
                    order:2,
                    content:"两，两边都看不见啦！"
                }
             },
             //许褚
            'xuzhu':{
                'luoyi':{
                    order:1,
                    content:'脱！<br>谁来与我大战三百回合。',
                },
                'die':{
                    order:2,
                    content:"冷，好冷啊。",
                }
            },
            //张辽
            'zhangliao':{
                'tuxi':{
                    order:1,
                    content:'哼，没想到吧！<br>拿来吧！',
                },
                'die':{
                    order:2,
                    content:"真的没想到。",
                }
            },
            //甄姬
            'zhenji':{
                'luoshen':{
                    order:1,
                    content:"髣髴兮若轻云之蔽月。<br>飘飖兮若流风之回雪。",
                },
                'qingguo':{
                    order:2,
                    content:'凌波微步，罗袜生尘。<br>体迅飞凫，飘忽若神。',
                },
                'die':{
                    order:3,
                    content:"悼良会之永绝兮，哀一逝而异乡。"
                }
             },
             //关羽
            'guanyu':{
                'wusheng':{
                    order:1,
                    content:'看尔乃插标卖首。<br>关羽在此，尔等受死。',
                },
                'die':{
                    order:2,
                    content:"什么，此地名叫麦城。",
                }
            },
            //黄月英
            'huangyueying':{
                'jizhi':{
                    order:1,
                    content:"哼哼~<br>呵~",
                },
                'qicai':{
                    order:2,
                    content:'',
                },
                'die':{
                    order:3,
                    content:"亮~"
                }
             },
            //刘备
            'liubei':{
                'rende':{
                    order:1,
                    content:'惟贤惟德，能服于人。<br>以德服人。',
                },
                'jijiang':{
                    order:2,
                    content:"蜀将何在？<br>尔等敢应战否？",
                },
                'die':{
                    order:3,
                    content:"这就是……桃园吗？",
                }
            },
            //马超
            'machao':{
                'mashu':{
                    order:1,
                    content:'',
                },
                'tieji':{
                    order:2,
                    content:"（马嘶鸣）<br>全军突击！",
                },
                'die':{
                    order:3,
                    content:"（马蹄声远去……）",
                }
            },
            //张飞
            'zhangfei':{
                'paoxiao':{
                    order:1,
                    content:"燕人张飞在此！<br>啊啊啊啊！",
                },
                'die':{
                    order:2,
                    content:"实在是，杀不动了。"
                }
             },
            };
    lib.qhly_sanguoskininfo = {};
});